dist: trusty
sudo: required

language: c
compiler:
    - gcc

install:
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq libcunit1 libcunit1-dev

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test

after_success:
    - bash <(curl -s https://codecov.io/bash) -F unittests || echo "Codecov did not collect coverage reports"
